@startuml
    class Main {
        +main(String[] args) void
    }
    
    class Libro {
        -String titulo
        -String autor
        -int añop
            
        +Libro(String titulo, String autor, int añop)
        +getAutor() String
        +getTitulo() String
        +getAñop() int
        +setAutor(String autor) void
        +setTitulo(String titulo) void
        +setAñop(int añop) void
        +verificaraño() void
    }
    
    Main ..> Libro : uses
@enduml